name: .NET

on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: UnitTests

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
    - name: Codecov upload
      run: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe 
          -Outfile codecov.exe 
          .\codecov.exe -t ${b54207e1-0b6a-497a-93ea-cdf05d2a129e}
